title: Verve Dialog
description: Verve Dialog 的使用文档
theme: just-the-docs

url: https://chen-xi-g.github.io/

aux_links:
  Github: https://github.com/Chen-Xi-g/VerveDialog

favicon_ico: "/assets/images/verve-dialog-ico.ico"

enable_copy_code_button: true

back_to_top: true

back_to_top_text: "返回到顶部"

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

plugins:
  - jekyll-tabs